//! Generate a starter least-privilege Sentinel policy from probed tools.
//!
//! The output is a real, loadable `sentinel-policy` document: destructive
//! tools denied, outward-facing tools routed to approval, read-style tools
//! allowed, everything else falling through to `default_action: deny`.

use sentinel_policy::{Effect, Match, PolicyDoc, Risk, Rule};

use crate::probe::ProbedServer;

const READ_PREFIXES: &[&str] = &["get_", "list_", "search_", "read_", "fetch_", "describe_"];
const DESTRUCTIVE_MARKERS: &[&str] = &[
    "delete", "drop", "remove", "destroy", "wipe", "purge", "truncate", "exec", "shell",
    "run_command", "eval",
];
const OUTBOUND_MARKERS: &[&str] = &[
    "send", "post_", "publish", "email", "tweet", "upload", "transfer", "pay", "charge", "wire",
];

/// Build one policy document covering all probed servers.
pub fn generate(probed: &[ProbedServer]) -> PolicyDoc {
    let mut rules = Vec::new();
    for server in probed {
        let mut destructive = Vec::new();
        let mut outbound = Vec::new();
        let mut reads = Vec::new();
        for tool in &server.tools {
            let Some(name) = tool.get("name").and_then(serde_json::Value::as_str) else {
                continue;
            };
            let lower = name.to_lowercase();
            if DESTRUCTIVE_MARKERS.iter().any(|m| lower.contains(m)) {
                destructive.push(name.to_string());
            } else if OUTBOUND_MARKERS.iter().any(|m| lower.contains(m)) {
                outbound.push(name.to_string());
            } else if READ_PREFIXES.iter().any(|p| lower.starts_with(p)) {
                reads.push(name.to_string());
            }
        }
        if !destructive.is_empty() {
            rules.push(rule(
                format!("{}-deny-destructive", server.name),
                &server.name,
                destructive,
                Effect::Deny,
                Some(Risk::High),
                Some("Destructive operations require a human at the keyboard".into()),
            ));
        }
        if !outbound.is_empty() {
            rules.push(rule(
                format!("{}-approve-outbound", server.name),
                &server.name,
                outbound,
                Effect::Approve,
                Some(Risk::High),
                Some("Outward-facing actions require pre-action approval".into()),
            ));
        }
        if !reads.is_empty() {
            rules.push(rule(
                format!("{}-allow-reads", server.name),
                &server.name,
                reads,
                Effect::Allow,
                Some(Risk::Low),
                None,
            ));
        }
    }
    PolicyDoc {
        version: 1,
        default_action: Effect::Deny,
        rules,
    }
}

fn rule(
    id: String,
    server: &str,
    tools: Vec<String>,
    action: Effect,
    risk: Option<Risk>,
    reason: Option<String>,
) -> Rule {
    Rule {
        id,
        description: None,
        matcher: Match {
            server: Some(server.to_string()),
            tools: Some(tools),
            agents: None,
            principals: None,
            args: Vec::new(),
        },
        action,
        risk,
        reason,
    }
}

/// Render the document as YAML with an explanatory header.
pub fn render(doc: &PolicyDoc) -> anyhow::Result<String> {
    let yaml = serde_yaml::to_string(doc)?;
    Ok(format!(
        "# Starter Sentinel policy generated by sentinel-scan from the live tool\n\
         # surface. Review before use — especially tools that fell through to the\n\
         # default deny: grant them explicitly if your agent needs them.\n\
         #   validate:  sentinel-gateway policy check --policy <this file>\n\
         #   dry-run:   sentinel-gateway policy eval --policy <this file> --server <s> --tool <t> --args '{{...}}'\n\
         {yaml}"
    ))
}

#[cfg(test)]
mod tests {
    use super::*;
    use sentinel_policy::{CallCtx, Policy};
    use serde_json::json;

    fn probed() -> ProbedServer {
        ProbedServer {
            name: "email".into(),
            server_info: None,
            tools: vec![
                json!({"name": "send_email"}),
                json!({"name": "list_inbox"}),
                json!({"name": "delete_all_emails"}),
                json!({"name": "summarize_thread"}),
            ],
        }
    }

    #[test]
    fn generated_policy_loads_and_enforces_least_privilege() {
        let doc = generate(&[probed()]);
        let text = render(&doc).unwrap();
        let policy = Policy::from_yaml(&text).expect("generated policy must be valid");

        let args = json!({});
        let eval = |tool: &str| {
            policy
                .evaluate(&CallCtx {
                    server: "email",
                    tool,
                    agent: "a",
                    principal: "p",
                    args: &args,
                })
                .effect
        };
        assert_eq!(eval("delete_all_emails"), Effect::Deny);
        assert_eq!(eval("send_email"), Effect::Approve);
        assert_eq!(eval("list_inbox"), Effect::Allow);
        // Unclassified tools fall through to default deny.
        assert_eq!(eval("summarize_thread"), Effect::Deny);
    }

    #[test]
    fn empty_probe_yields_default_deny_only() {
        let doc = generate(&[]);
        assert!(doc.rules.is_empty());
        assert_eq!(doc.default_action, Effect::Deny);
        Policy::from_yaml(&render(&doc).unwrap()).unwrap();
    }
}
